- name: Setup gpg key
  apt_key:
    url: https://downloads.avax.network/node.gpg.key
    state: present

- name: Setup node repo
  apt_repository:
    repo: deb https://downloads.avax.network/apt focal main
    state: present

- name: Setup golang repo
  apt_repository:
    repo: ppa:longsleep/golang-backports 
    state: present

- name: Install go
  apt:
    name: golang
    state: latest

- name: Update git clone
  git:
    repo: "{{ repo_url }}"
    dest: "{{ repo_folder }}"
    version: "{{ tag }}"
    update: yes
    force: yes

- name: Setup systemd
  template:
    src: templates/node.service.j2
    dest: /etc/systemd/system/node.service
    mode: 0755

- name: Create lux user
  user:
    name: "{{ lux_user }}"
    shell: /bin/bash
    uid: 114
    group: "{{ lux_group }}"

- name: Create lux config dir
  file:
    path: /etc/node
    owner: "{{ lux_user }}"
    group: "{{ lux_group }}"
    state: directory

- name: Create lux C config dir
  file:
    path: /etc/node/C
    owner: "{{ lux_user }}"
    group: "{{ lux_group }}"
    state: directory

- name: Create lux log dir
  file:
    path: "{{ log_dir }}"
    owner: "{{ lux_user }}"
    group: "{{ lux_group }}"
    state: directory

- name: Create lux database dir
  file:
    path: "{{ db_dir }}"
    owner: "{{ lux_user }}"
    group: "{{ lux_group }}"
    state: directory

- name: Create lux plugins directory
  file:
    path: "{{ plugin_dir }}"
    owner: "{{ lux_user }}"
    group: "{{ lux_group }}"
    state: directory
    recurse: yes

- name: Build node
  command: ./scripts/build.sh
  args:
    chdir: "{{ repo_folder }}"

- name: Copy node binaries to the correct location
  command: cp build/node /usr/local/bin/node
  args:
    chdir: "{{ repo_folder }}"

- name: Copy evm binaries to the correct location
  command: cp build/plugins/evm {{ plugin_dir }}
  args:
    chdir: "{{ repo_folder }}"


- name: Configure lux 
  template:
    src: templates/conf.json.j2
    dest: /etc/node/conf.json
    mode: 0644

- name: Configure lux C Chain
  template:
    src: templates/C/config.json.j2
    dest: /etc/node/C/config.json
    mode: 0644

- name: Enable Lux
  systemd:
    name: node
    enabled: yes
