name: Lint proto files

on:
  push:

permissions:
  contents: read

jobs:
  buf-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
<<<<<<< HEAD
<<<<<<< HEAD
      - uses: bufbuild/buf-setup-action@v1.11.0
        with:
          github_token: ${{ github.token }}
=======
      - uses: bufbuild/buf-setup-action@v1.9.0
>>>>>>> 51f21a85b (Update buf to v1.9.0 (#2239))
=======
      - uses: bufbuild/buf-setup-action@v1.9.0 # TODO: use "v1.10.0"
>>>>>>> 1c0e00460 (Bump buf dependency to v1.10.0 (#2339))
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: "proto"
